### ISSUE TITLE
Bug with checkbox field

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-checkout-fields#147]
https://github.com/easydigitaldownloads/edd-checkout-fields/issues/45#issuecomment-340919972

If I have a required checkbox, with multiple items, and I only check one of the items...it doesn't validate HTML5:
![screen shot 2017-10-31 at 2 56 14 pm](https://user-images.githubusercontent.com/1390124/32250931-c7d4bf38-be4b-11e7-9e3b-2cecf893ef96.png)

**Comment by SDavisMedia** [comment]
This problem was introduced when we added `required` attributes to form fields: https://github.com/easydigitaldownloads/edd-checkout-fields/issues/132

That wasn't a bad move but it gets kinda tricky with CFM fields. What ends up happening is each individual checkbox/radio input gets its own required attribute instead of just ensuring that at least one of them is selected.

Here's the thing, though... CFM already accounted for this. Instead of HTML5 validation, it throws a checkout error:

<img width="766" alt="screenshot 2018-02-28 11 53 03" src="https://user-images.githubusercontent.com/2359131/36809829-f44882e4-1c7d-11e8-9ffe-e4694480f0be.png">

I personally see nothing wrong with reverting back to the built-in system for both checkout and radio fields.
