### ISSUE TITLE
Purchase confirmation not showing user-saved fields

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-checkout-fields#148]
The purchase confirmation page is not showing user-saved fields after checkout.

Before Checkout (fields are filled out):
<img width="449" alt="screen shot 2017-11-12 at 5 27 26 pm" src="https://user-images.githubusercontent.com/1638128/32704172-d8aa59b2-c7ce-11e7-9520-b032021bd6b0.png">

After Checkout (fields are blank):
<img width="494" alt="screen shot 2017-11-12 at 5 27 37 pm" src="https://user-images.githubusercontent.com/1638128/32704175-e5a03a6a-c7ce-11e7-8a5d-67417cc1fc9a.png">

I noticed that the fields which are blank are all user meta fields (not payment meta fields). Possibly related: https://github.com/easydigitaldownloads/edd-checkout-fields/issues/138

Note that the fields did correctly populate the Customer's information (First/Last Name etc):
<img width="879" alt="screen shot 2017-11-12 at 5 33 31 pm" src="https://user-images.githubusercontent.com/1638128/32704215-a52dd9b4-c7cf-11e7-98ba-1372c56e338f.png">

Additionally, I tested without the checkbox field because I know checkboxes are prone to cause strange issues. However, removing the checkbox field had no affect so I don't believe it is checkbox related. 

If someone else could test to confirm that would be great. 

Testing Steps:
1. Make sure your settings for the Checkout Fields Manager plugin are set to show the fields on the Purchase Confirmation page. 
2. In your checkout fields manager add First/Last Name fields. Also add an email field, a text field which is saved to the user meta, and a field which is saved to the payment meta. 
3. Purchase the product with all fields filled out. 
4. Check if the purchase confirmation page shows the entered data or if it is blank.

**Comment by dgoldak** [comment]
Related ticket: https://secure.helpscout.net/conversation/521404813/75875?folderId=1847242

**Comment by SDavisMedia** [comment]
I'm curious if this was ever supposed to show name and email address values on purchase confirmation. The logic seems to depend on the meta type setting for each field, which is not an available setting for the default fields... only newly fields. Seems like this was an oversight.

I can't replicate any custom fields not showing on purchase confirmation. They all seem to work, whether the meta type is payment or user (customer).

**Comment by SDavisMedia** [comment]
Alright, I've got some concerns about the overall functionality of this feature (showing purchase data on purchase receipt) but I wanted to take a stab at it anyway just for practice. Here are my concerns:

1. Do we actually want to show the standard fields (first name, last name, and email)? It _feels_ unnecessary but I could honestly lean either way.

2. For logged out customers, personal info will show on the receipt thanks to my patch above, but custom fields won't show if the values are saved as user info instead of payment info. I feel like we can do something about that. Perhaps this issue is relevant? https://github.com/easydigitaldownloads/edd-checkout-fields/issues/125

I think that's it for now. Again, I'm not 100% confident in my approach here but I wanted to give it a try and risk getting it wrong rather than not try at all.

**Comment by pippinsplugins** [comment]
1. My first reaction is to not show them, but then looking at your screenshot above, it would make sense to show them if it's in the context of collecting company or other personal information.

2. I definitely think we should make it consistent regardless of where the data is stored.

I think your approach is fine!

**Comment by kerijacoby** [comment]
https://secure.helpscout.net/conversation/529282241/76777?folderId=180499
